# set `baseurl` to your root domain
# if you set it to "/" share icons won't work properly on production
baseurl = "https://yjinheon.github.io/"   # include trailing slash
# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright ©, Yjinheon the Hugo Authors; all rights reserved."
# canonifyurls = true
paginate = 10
theme = "DoIt"
disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]


[params.home.profile]
  enable = true
  # Gravatar Email for preferred avatar in home page
  gravatarEmail = ""
  # URL of avatar shown in home page
  avatarURL = "/images/medium.jpg"
  # URL the avatar links to
  avatarLinkURL = ""
