version: "3.4"

services:
  search_api:
    container_name: search
    image: dybaek411/basic-engine:0.7
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '4'
        reservations:
          cpus: '3'
    volumes:
      - search_v:/workspace/
      - search_log_v:/var/log/
      - search_nginx_v:/home/
      - search_logstash_config_v:/etc/logstash/
      - search_logstash_bin_v:/usr/share/logstash
      - cron_v:/etc/cron.d
    ports:
      - "80:80"
      - "9922:22"
      - "1234:8000"
      - "8888:8888"
    networks:
      - search_eco
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 50s
      timeout: 20s
      retries: 5
      start_period: 180s
    command: sh -c "service ssh start && cp /home/nginx.conf /etc/nginx/nginx.conf && cd /etc/nginx/sites-enabled && unlink default &&
                    sudo service nginx start && chmod 777 /etc/cron.d/search_cron &&
                    service cron start && crontab /etc/cron.d/search_cron && cd /workspace/search &&
                    gunicorn -k uvicorn.workers.UvicornWorker search_api_v2:app --max-requests 36 --max-requests-jitter 36 --bind 0.0.0.0:8000 --workers 7 --threads 3 --daemon --preload &&
                    cp -r /etc/logstash/mysql-connector-java-8.0.23 /usr/share/logstash/lib &&
                    sudo service logstash start && /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/epis-search-log.conf"
    stdin_open: true
    tty: true

 mysql_db:
    container_name: mysql
    image: mysql:8.0.23
    restart: always
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
        reservations:
          cpus: '0.5'
    volumes:
      - mysql_init_v:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sys
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    networks:
      - search_eco
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 180s
    stdin_open: true
    tty: true


volumes:
  search_v:
    external: true
  search_log_v:
    external: true
  search_nginx_v:
    external: true
  search_logstash_config_v:
    external: true
  search_logstash_bin_v:
    external: true

  mysql_init_v:
    external: true

  cron_v:
    external: true

networks:
  search_eco: