version: "3.4"

services:
  search_api:
    container_name: search
    image: dybaek411/basic-engine:0.7
    volumes:
      - search_v:/workspace/
      - search_log_v:/var/log/
      - search_nginx_v:/home/
      - search_logstash_config_v:/etc/logstash/
      - search_logstash_bin_v:/usr/share/logstash
      - cron_v:/etc/cron.d
    ports:
      - "80:80"
      - "9922:22"
      - "1234:8000"
      - "8888:8888"
    networks:
      - search_eco
    stdin_open: true
    tty: true

  mysql_db:
    container_name: mysql
    image: mysql:8.0.23
    volumes:
      - mysql_init_v:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: sys
      MYSQL_ROOT_PASSWORD: 1234
      TZ: Asia/Seoul
    networks:
      - search_eco
    stdin_open: true
    tty: true

volumes:
  search_v:
    external: true
  search_log_v:
    external: true
  search_nginx_v:
    external: true
  search_logstash_config_v:
    external: true
  search_logstash_bin_v:
    external: true

  mysql_init_v:
    external: true

  cron_v:
    external: true

networks:
  search_eco:
    driver: bridge    